### PR TITLE
Small improvements to gatsby-node

### PR DESCRIPTION
**Pull request by dajocarter**
I queried categories and tags separately from posts by filtering for only those with count greater than 0 which means it's attached to at least one post. 
Once I did that, there wasn't a need for lodash so I removed that.
I also checked for the production environment to only create pages for published posts and pages.

### CODE REVIEW

**Comment by chmac** [comment]
@dajocarter Thanks for getting involved, great to see so many PRs.

On the lodash front, it's only used at build time, so doesn't affect the user experience of loading the site. It was a deliberate choice to favour lodash over the native `forEach()`. I find lodash's handling of undefined, null, etc much nicer than the native approach.

The change to only build published pages is an interesting one. I think you're definitely onto something here. It does make sense to ignore draft pages, etc from the built output. However, I'm not sure if it makes sense to include them in development but hide them in production. I imagine this is the kind of hidden change that can create confusion. Why do I see X here but only Y there? It's the kind of thing I guess would need to be well documented.

The starter itself doesn't actually get to see draft posts, because they're excluded from the anonymous response by WordPress. If you authenticate against your WordPress site, then I imagine they might be included.

You've definitely brought up a good point with this. I'll contemplate it on it a bit and see what I can come up with in terms of how to approach it.

**Comment by chmac** [comment]
Just noticed you're also building the category and tag pages from the WordPress data directly, instead of iterating over the posts array. That's an interesting idea. Would mean that category pages exist even if they don't contain any posts. Could make sense.

**Comment by dajocarter** [comment]
> Would mean that category pages exist even if they don't contain any posts.

I added a filter in the category and tag queries for count > 0, so it'll only fetch those that do contain posts.

Having pages for empty categories and tags could be a use case for someone, but it's also simple enough to remove the filter if you need those pages. I just did it this way to replicate what I was replacing.

Another thought I had was filtering out the 'uncategorized' category, but that seems like another case where someone might want that page.

**Comment by chmac** [comment]
@dajocarter The merge conflicts turned out to be pretty messy here, so I copied and pasted the changes into new commits and pushed them to master with a link to this PR. I think I got all the significant changes, so I'll close this PR. Just let me know if I missed anything.

**Pull request closed without merging**
