### PR TITLE
Create nested paths for pages

### LINKED ISSUE #24: Child pages and child categories don't have the parent slug in the URL
Child pages and categories should have their parent's slug prepended in the URL

**Expected**
The URL for a child page should be `whatever.com/grandparent-page/parent-page/child-page/`

**Current**
The URL for a child page is `whatever.com/child-page`

I can submit a PR for this

### PR DESCRIPTION
**Pull request by dajocarter**
This closes #24

### CODE REVIEW

**Comment by chmac** [comment]
@dajocarter Another great point. Nested page paths makes sense.

There's no guarantee that every WordPress page's parent(s) are actually published themselves. I've just created a quick test on our demo site. It has a top level page "Draft" which is in draft state, and that page has a child called "Child of Draft" which is itself published. This causes your branch to crash on boot.

I'm not sure what the best approach is here. If the WordPress site has permalinks setup, then the `link` property of the page will contain the page's full "path". But if not, it will have a link like `?page_id=X` which doesn't help us.

I think this is another one I'll need to contemplate on for a few days and see what comes up...

**Comment by dajocarter** [comment]
I added a commit to check for the parent page before prepending the slug to the path. If the parent page doesn't exist, then child page still gets a path of `/child-page/` and if the grandparent page doesn't exist, then it gets `/parent-page/child-page/`, and so on.

**Comment by chmac** [comment]
That's an interesting idea. Under that scenario when I publish the parent post, it's children will get a new path on Gatsby. Not sure if that makes sense. I'm wondering if we need to make pretty permalinks a hard requirement for the starter, and then extract the full path out of the `link` property...

**Comment by dajocarter** [comment]
Another good catch, I didn't think about that. Using the `link` property would probably be the way to go then. I just added a commit for that, but I feel like we should be using environment variables to set the protocol and base url then we can use that in `gatsby-config` and `gatsby-node`. I wasn't sure if you wanted to do that though.

**Comment by chmac** [comment]
@dajocarter Added a commit which extracts the base URL from the config file, saves having to hard code it.

**Comment by chmac** [comment]
Thanks for the call today. Was great to connect.

Here's the notes I took on the changes we discussed.

* [ ] Switching to `url.parse()` instead of `.replace()` seems to make sense
* [ ] After parsing the `link` we could test
  - If `url.search === null` then we can use `url.pathname` as the `path` field
  - If not, then we use `slug` as the `path` field
* [ ] Same logic could apply to categories and pages
* [ ] Would also be great to add some simple tests on this `getPathFromPost()` helper

**Comment by chmac** [comment]
@dajocarter I've merged `master` into this branch and fixed the merge conflict, including the changes I copied from your `gatsby-node` branch, hopefully it's all set to make the changes we talked about today.

**Comment by dajocarter** [comment]
So one thing I found out in testing the plain permalinks option is that gatsby-source-wordpress doesn't support it. Seems like we can either continue and future-proof the starter, or move forward with the assumption that pretty permalinks is turned on.
https://github.com/gatsbyjs/gatsby/issues/1871
https://github.com/gatsbyjs/gatsby/pull/5053

**Comment by chmac** [comment]
@dajocarter Yeah, I’ve seen that the source plugin assumes the path is `/wp-json/`. That seems like a definite bug to me, and one that’s likely very easy to fix. The alternate syntaxc is `/?rest_route=/` and this will work on both plain permalinks and “pretty” permalinks, so it seems like an obvious upgrade to me. I might even get around to submitting a PR at some point to change that.

I imagine it’s worth supporting plain permalink WP installs given the reasonably small amount of extra effort. I can also imagine that if one setups a fresh WP install to use as a content repo, the extra effort (albeit a small effort) of setting up permalinks might not be worth it just to serve content.

**Comment by nachiketkumar** [comment]
hello! Any chance this PR is going to get merged to make nested paths work for #24 ?

**Comment by chmac** [comment]
@nachiketkumar It's not yet ina state where it's ready to be merged. Are you open to pushing it forward?

The topic of nested paths is a slightly complex one. If you think the approach in this PR is what you want, you could merge it into your own fork and then use that as your starter.

**Pull request closed without merging**
